-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_ALPIDE_regs is

  constant IPBUS_SEL_WIDTH: positive := 5;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_ALPIDE_regs(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Wed Jan 29 08:41:30 2020 
  constant N_SLV_DATA: integer := 0;
  constant N_SLV_CSR: integer := 1;
  constant N_SLV_CMD_ADDR: integer := 2;
  constant N_SLAVES: integer := 3;
-- END automatically generated VHDL

    
end ipbus_decode_ALPIDE_regs;

package body ipbus_decode_ALPIDE_regs is

  function ipbus_sel_ALPIDE_regs(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Wed Jan 29 08:41:30 2020 
    if    std_match(addr, "------------------00------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_DATA, IPBUS_SEL_WIDTH)); -- DATA / base 0x00000000 / mask 0x00003000
    elsif std_match(addr, "------------------10------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- CSR / base 0x00002000 / mask 0x00003000
    elsif std_match(addr, "------------------11------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CMD_ADDR, IPBUS_SEL_WIDTH)); -- cmd_addr / base 0x00003000 / mask 0x00003000
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_ALPIDE_regs;

end ipbus_decode_ALPIDE_regs;

