# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/CMD_ROM/CMD_ROM.xci
# IP: The module: 'CMD_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/CMD_ROM/CMD_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CMD_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/CMD_ROM/CMD_ROM.xci
# IP: The module: 'CMD_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/CMD_ROM/CMD_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CMD_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
