# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO.xci
# IP: The module: 'DATA_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO.xci
# IP: The module: 'DATA_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDEN2/ALPIDEN2.srcs/sources_1/ip/DATA_FIFO/DATA_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
