webtalk_init -webtalk_dir D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.sim/sim_1/behav/xsim/xsim.dir/ALPIDE_Carrier_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 24 14:14:51 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0b0731a2-f748-4f09-88d9-500977a228bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ccc19e1945b84675998edd886920c9eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "169" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4391 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.55_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1198580503 -regid "" -xml D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.sim/sim_1/behav/xsim/xsim.dir/ALPIDE_Carrier_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.sim/sim_1/behav/xsim/xsim.dir/ALPIDE_Carrier_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.sim/sim_1/behav/xsim/xsim.dir/ALPIDE_Carrier_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
