# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL.xci
# IP: The module: 'R_W_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL.xci
# IP: The module: 'R_W_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/Progetto/firmware/Lab9.srcs/sources_1/ip/R_W_PLL_1/R_W_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'R_W_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
