# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter.xci
# IP: The module: 'phase_shifter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter.xci
# IP: The module: 'phase_shifter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Progetti_vivado/ALPIDE_Reader/ALPIDE_Reader.srcs/sources_1/ip/phase_shifter/phase_shifter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'phase_shifter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
