# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (gcu_v2_fw_v0.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.cache/wt [current_project]
set_property parent.project_path D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/Mem_init_file/ROM_initialization.mem
read_verilog -library xil_defaultlib {
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/Inner_module/ROM_INIT.v
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/Inner_module/DATA_FIFO.v
}
read_vhdl -library xil_defaultlib {
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_fifo_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_ten_100_1g_eth_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_support.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_reset_sync.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_tx_client_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_rx_client_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_bram_tdp.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/imports/tri_mode_ethernet_mac_0_sync_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_status_buffer.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_txtransactor_if_simple.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_decode_arty7_regs.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_reg_v.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/system_clocks.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_ipaddr_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_build_arp.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_packet_parser.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_fabric_sel.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_build_resend.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_package.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_byte_sum.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_rarp_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/Inner_module/send_byte.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_ctrlreg_v.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_tx_mux.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_rx_client_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_build_status.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_do_rx_reset.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_build_payload.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/Inner_module/RW_PLL.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_reg_types.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_build_ping.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/Inner_module/read_byte.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_rxtransactor_if_simple.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_fabric.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_mii_if.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_trans_decl.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/transactor_cfg.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/trans_arb.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_addr_decode.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_ctrl.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_clock_crossing_if.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_dualportram_tx.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/stretcher.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_dpram.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_tx_client_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/ipbus_fabric_simple.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/transactor.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_ten_100_1g_eth_fifo.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/transactor_sm.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_dualportram.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/ALPIDE_reader_module/ALPIDE_Carrier.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_if_flat.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/clock_div.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_dualportram_rx.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_rxram_shim.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/transactor_if.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_rxram_mux.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Top/top_level.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_sync_block.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/udp_buffer_selector.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/ALPIDE_sources/Ipbus/tri_mode_eth_mac_v5_5_reset_sync.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/imports/Ipbus/ipbus_decode_ALPIDE_regs.vhd
  D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/new/CDC_module.vhd
}
read_ip -quiet D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/tri_mode_ethernet_mac_0.xci
set_property used_in_implementation false [get_files -all d:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0.xdc]
set_property used_in_implementation false [get_files -all d:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/sources_1/ip/tri_mode_ethernet_mac_0_2/synth/tri_mode_ethernet_mac_0_clocks.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/constrs_1/imports/constrs_1/mapping.xdc
set_property used_in_implementation false [get_files D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/constrs_1/imports/constrs_1/mapping.xdc]

read_xdc D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/constrs_1/imports/constrs_1/timing.xdc
set_property used_in_implementation false [get_files D:/Progetti_vivado/ALPIDE_on_ARTY_V05/ALPIDE_on_ARTY_V05.srcs/constrs_1/imports/constrs_1/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a35tcsg324-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
